services:
  - type: web
    name: rinconcito-laravel
    env: docker
    plan: free
    region: oregon
    branch: main
    rootDir: .
    dockerContext: .
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        value: base64:TU_APP_KEY_GENERADA
      - key: APP_URL
        value: https://rinconcito-laravel.onrender.com

      # Configuración de base de datos (ajústala a tu base de datos real)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tu-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: tu-nombre-bd
      - key: DB_USERNAME
        value: tu-usuario
      - key: DB_PASSWORD
        value: tu-contraseña

      # Otros drivers
      - key: SESSION_DRIVER
        value: file
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      - key: LOG_CHANNEL
        value: errorlog
